services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_cendana
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel    

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx_cendana
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
